### ISSUE TITLE
Support creation of databases in Firebird

### ISSUE THREAD

**Issue by hhindriks** [DbUp/dbup-firebird#1]
Support creating databases with the 

`
EnsureDatabase.For.FirebirdDatabase(connectionString);
`

call. I am working on implementing them. Hopefully a PR will follow soon.

**Comment by Jeern** [comment]
@sungam3r and @mjauernig  I always ended up implementing something like this when I have used DbUp. But its something you would only do in development or in temporary environments not in a "real"  environment like production. So I am not sure it should be a part of DbUp - if so I think it should be a thing for all providers not firebird only. 

Today for local development I prefer to use a docker image to create the database - it is built into the https://hub.docker.com/r/jacobalberty/firebird image so then there is no reason to do it in DbUp.

**Comment by Jeern** [comment]
@sungam3r and @mjauernig  Hmm... I can see that EnsureDatabase  is already a part of DbUp-core so then my comment is not as valid. The PR DbUp/DbUp#365 has some of the same fixes I provided in DbUp/DbUp#692

**Comment by mjauernig** [comment]
@Jeern So we should merge DbUp/DbUp#365 to?

**Comment by Jeern** [comment]
@mjauernig  No not before I have taken a look at it. According to the description it would conflict with what I have already done (perhaps not in GIT but functionally)

**Comment by MarvinKlein1508** [comment]
Do you have any plans to support this? :)

**Comment by Jeern** [comment]
I have been out og the loop for a while so I don't know what the general plans are. I was working on a PR almost a year ago but got sidetracked by work. I really really hope I will be able to prioritize it in august.

**Comment by droyad** [comment]
Yes, I think we should support this.

**Comment by Jeern** [comment]
I have implemented and tested this in a local branch. Just waiting for @droyad  to give me permissions to push to dbup-firebird and create a PR (or tell me that I have to Fork )

**Comment by Jeern** [comment]
I have pushed the branch but will wait for https://github.com/DbUp/dbup-firebird/pull/7 to be merged before I create a PR (since I had to create the branch from that branch while waiting for Push permissions)
